librinfo_varieties:
    variety_descriptions:
########### CONSEILS PROS ##################
        professional:
            possible_sowing_periods: ~
            germination_conditions: ~
            transplant: ~
            sowing_density: ~
            on_line_distance: ~
            between_distance: ~
            exposure: 
                type: choice
                options:
                    choices:
                        - nord
                        - sud
            seedling_irrigation:
            transplant_irrigation: ~
            manure: ~
            cuttings_period: ~
            cutting_date: ~
            sowing_date: ~
            transplant_date: ~
            transplant_manure_quantity: ~
            substratum: ~
            treatments: ~
            seed_storage: ~
            harvest_storage: ~
            advised_outcome: ~
            possible_outcome: ~
            soil: ~
            yield:
                options:
                    help: librinfo.help.yield
            biodynamics: ~  
            tutoring: ~
############# CONSEILS AMATEURS ####################
        amateur:
            possible_sowing_periods: ~
            germination_conditions: ~
            seed_storage: ~
            transplant: ~
            sowing_density: ~
            on_line_distance: ~
            between_distance: ~
            seedling_irrigation: ~
            exposure: ~
            manure: ~
            soil: ~
            yield: ~
            biodynamics: ~
########### MISE EN PRODUCTION ##################
        production:
            possible_sowing_periods: ~
            germination_conditions: ~
            transplant: ~
            sowing_density: ~
            on_line_distance: ~
            between_distance: ~
            exposure: 
                type: choice
                options:
                    choices:
                        - nord
                        - sud
            seedling_irrigation:
            transplant_irrigation: ~
            manure: ~
            cuttings_period: ~
            cutting_date: ~
            sowing_date: ~
            transplant_date: ~
            transplant_manure_quantity: ~
            substratum: ~
            treatments: ~
            seed_storage: ~
            harvest_storage: ~
            advised_outcome: ~
            possible_outcome: ~
            soil: ~
            yield:
                options:
                    help: librinfo.help.yield
            biodynamics: ~  
            tutoring: ~
########## TRI OFFRE COMMERCIAL ###################
        commercial: 
            taste_rating: ~
            taste: ~
            texture: ~
            nutrition_rating: ~
            nutrients: 
            main_color: ~
            secondary_color: ~
            yield: ~
            max_harvest_span: ~
            min_harvest_span: ~
            prefered_zone: ~
            # calibre
            grade: ~
            main_usages: ~
            usages: ~
            plant_type: ~
            targeted_audience: ~
            precocity: ~
            rusticicty: ~
            cultivation_ease: ~
            pot_cultivation_ease: ~
            inner_commment: ~
 ############# CARACTERISTIQUES PLANTE #############
        plant: 
            foliage_type: ~
            foliage_color: ~
            required_size: ~    
 ############## CULTURE ############################
        culture:
            location: ~
            
            
            
            
            
            
           